export const APP_NAME = 'PDF-UP';

export const HTTP_STATUS_CODE = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,
  GONE: 410,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  PAYMENT_REQUIRED: 402,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  CONFLICT: 409,
  PAYLOAD_TOO_LARGE: 413,
  UNSUPPORTED_MEDIA_TYPE: 415,
  TOO_MANY_REQUESTS: 429,

  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
} as const;

export const SUCCESS_MESSAGES = {
  USER_REGISTERED: 'User registered successfully',
  OTP_SENT: 'OTP sent successfully',
  OTP_VERIFIED: 'OTP verified successfully',
  USER_LOGGED_IN: 'User logged in successfully',
  TOKEN_REFRESHED: 'Token refreshed successfully',
  USER_LOGGED_OUT: 'User logged out successfully',
  PDF_UPLOADED: 'PDF uploaded successfully',
  PDF_GENERATED: 'PDF generated successfully',
  PDF_DELETED: 'PDF deleted successfully',
  DOCUMENT_FETCHED: 'Successfully fetched document',
} as const;

export const ERROR_MESSAGES = {
  INVALID_OTP: 'Invalid OTP',
  EMAIL_REQUIRED: 'Email is required',
  EMAIL_NOT_VERIFIED: "Email not verified",
  EMAIL_AND_OTP_REQUIRED: 'Email and OTP are required',
  OTP_EXPIRED: 'OTP expired.',
  OTP_ALREADY_SENT: 'OTP already send',
  CREDENTIALS_NOT_SEND: 'Credentials not found',
  OTP_ABSENT: 'otp not present',
  OTP_NOT_MATCH: 'otp not match',
  PASSWORD_NOT_MATCH: 'confirm password and password are not matching.',
  PASSWORD_IS_WRONG: "Password is wrong",
  USER_ALREADY_EXISTS: 'User already exists.',
  USER_NOT_FOUND: 'User not found',
  ACCESS_TOKEN_NOT_FOUND: 'Access token is not found.',
  INVALID_ACCESS_TOKEN: 'Invalid access token.',
  CLOUDINARY_UPLOAD_FAILED: 'Cloudinary upload failure',
  REFRESH_TOKEN_MISSING: 'Refresh token missing',
  INVALID_REFRESH_TOKEN: 'Invalid refresh token',
  NO_PDF_UPLOADED: 'No PDF uploaded',
  UNAUTHORIZED: 'Unauthorized',
  INVALID_STORED_FILE_NAME: 'Invalid stored file name',
  PAGES_ARRAY_REQUIRED: 'Pages array required',
  INVALID_PAGE_NUMBERS: 'Invalid page numbers',
  INVALID_PDF_TYPE: 'Invalid pdf type',
  STORED_FILE_NAME_REQUIRED: 'Stored file name required',
  PDF_NOT_FOUND: 'PDF not found',
  PARENT_PDF_ID_MISSING: 'Parent PDF id missing',
  PDF_ID_MISSING: 'PDF id missing',
  INVALID_PAGE_SELECTED: 'Invalid page selected',
  FAILED_TO_SEND_OTP_EMAIL: 'Failed to send OTP email',
} as const;

export const CounterRepositoryKey = {
  USER: 'USER',
  PDF: 'PDF',
};
